language: ruby
rvm:
- 2.5
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: lSSDZK9XocB42UtHeX//y6V7w9Rm7ESltMTADY55drYXUn9aAz09GqrA6WkVXi55dtRyDwKp0t1htUbHMwBCyvTjtnbfzLxvWT6xAy9ZE4GfFqVK8OQ2jZHxtZimj/JLgRzTVPQUL/zLgb/aoV24bJCR2uzCaNYzt6Uq1xJBSWlV6jcznQT9l6pij4Tzx0XcbtIDe1Ia3rx1+NL+EUZLHQKZ4e59I5RwJ9WTjohqQ/EOligjYA01zuMPDKWB4wKaEvgm+uet7AM3ClU9ghqA+H5k86kwPhx1EuofqylSiq4v8Ndc6u2lOQu8gXF0BVCytTgcJG5qbwUNmPOKur5EnLnArqhbmIZPf/JwKO2A0AymkkV78FRp1zN8n8m4DmEmAssMCXlwExjZ4YMotiNZHwJBgtKMp8ZW3Kdixs1RI5Tx1+S3XEY/rGcDs1VDcfOktopKtJhrMoFpjj5rWpm3IkPmKVksusZFpsO/Zkv5w4XII1vDe53L963V2OVKWAEZBgbGgHLfWPMu26+6WZE/IO75o92m5E8WmOePRHerOqz8TTHUB2eKQGPSp9GqxMIjO/p3dDak8SIJ4Vd/wCikncFzxouWNL8HbTGahaKPjpVlIH93GCVtcgUkF0iC0nhFTeAZePJNUvRhJOHvgkSeXXzy5GzrYCGVGTFkJDDH5Dg=
