language: ruby
rvm:
- 2.5
branches:
  only:
  - master
install:
- bundle install
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination out
deploy:
  provider: pages
  local-dir: ./out
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master