language: ruby
rvm:
- 2.3.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: JyGRX1v8xuJJtITgYEUnr1Z2kuD7AJdWdDMu/8B7vdIzqn2gS9n5Nbeur+L2q8u49son8K/if/ua87AYlPMbzcewKZUIVjRqvs4LsmV+PBodWXJX6X9JSasr3nEhtwB/cvDX6b9F7M/kU3ZuAcJ3Fw35vbE5w+qLoGFfOZPr91S00rXHY0ZhZlLYEl9m0d25Uuyt5ejceQbnTMv9AKhKnDxoQwv0kLmV/yle7e1pT9bVXFdSNpefUFqyi9MXE/EpqWBTpYzBvsIXCeDaxczMPXgkb0IvwnFeeXKVjMjGTAOB5bM6EZRk2SBJ+byQrSyV4hVrhpfw7TCCfJJB+D1zXoUJ/ysgBTuNQZlCGdloW9CqOpxKrIA/8gye90zw2s3pfVgyMqDUHSbO2dUPMYhGNF7tiuDmaupaQqTokYUaMhCHyrwDmT7HmcJI6TLCWMKC/oAzYmJDLQpXSZ53DNq5Uk9MX4cusHjZZYp0Vd2QfNQ2JzIYrrsZDLKM1z0+qSe8WzVAROdm0y+r/JaAUcECRxnH1Gg3JJeNUH2MBf05bAzLM9ql5t7ar418u6pSyOo3GaduyzjvCVqln9RG100vVZoMd2lqZEptvYSx93MDH+sUPC+zIQHnc5paChnY3t8x0St8tIbpa+dAIwoB7z3iRMXT3G0grxCXQ0pb71pTs8o=
